version: "3"

services:

  shinyapp:
    image: somrc/shiny-lola
    networks:
      - net
    ports:
      - "80"
    volumes:
      - /data/lola/reference:/srv/shiny-server/shinyLOLA/reference
      - /data/lola/universes:/srv/shiny-server/shinyLOLA/universes
      - /data/lola/userSets:/srv/shiny-server/shinyLOLA/userSets
      - /data/lola/results:/srv/shiny-server/shinyLOLA/results
      - /data/lola/shinylog:/var/log/shiny-server
    deploy:
      mode: replicated
      replicas: 8
      resources:
        limits:
          memory: 12G
      labels:
        - "traefik.docker.network=ssp_net"
        - "traefik.port=80"
        - "traefik.frontend.rule=PathPrefix:/shinyLOLA;"
        - "traefik.backend.loadbalancer.sticky=true"

  loadbal:
    image: traefik
    command: --docker \
      --docker.swarmmode \
      --docker.watch \
      --web \
      --loglevel=DEBUG
    ports:
        - 80:80
        - 8080:8080
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 2G
      placement:
        constraints: [node.role == manager]
    networks:
      - net

networks:
  net:
